[package]
name = "sat-vi"
version = "0.1.0"
edition = "2024"

[[test]]
name = "tests"
path = "tests/tests.rs"

[dev-dependencies]
insta = { version = "1.43.2", features = ["filters", "glob"] }
rstest = "0.26.1"

